modLoader = "kotlinforforge"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CaelTheColher/Capes/issues"
license = "LGPL 2.1"

[[mods]]
modId = "capes"
version = "${version}"
displayName = "Capes"
authors = "Cael"
description = '''
A mod that lets you use capes from Optifine, LabyMod, Cosmetica, Wynntils, Capes++, and the MinecraftCapes Mod.
'''

[[dependencies.capes]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.capes]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "capes-common.mixins.json"
[[mixins]]
config = "capes-forge.mixins.json"